code/matt/django/lab02/accounts/urls.py
from django.urls import path
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    # path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

code/matt/django/lab02/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('accounts/', include('accounts.urls')),
]

code/matt/django/lab02/library/urls.py
from django.urls import path
from . import views

app_name = 'library'
urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('authors/<slug:slug>', views.author_detail, name='author_detail'),
    path('books/', views.books, name='books'),
    path('books/<slug:slug>', views.book_detail, name='book_detail'),
    path('history/', views.history, name='history'),
    path('genre/<slug:slug>', views.genre, name='genre'),
]

code/matt/django/lab02/accounts/models.py
from django.db import models

class User(models.Model):
    ...

code/matt/django/lab02/library/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=100)
    
    slug = models.SlugField()

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateField()
    author = models.ForeignKey(Author, on_delete=models.PROTECT, null=True)
    
    slug = models.SlugField()

    def __str__(self):
        return self.title

class Checkout(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='checkout_transaction')
    checkout = models.BooleanField(default=False, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return f'{self.book}_{self.checkout}_{self.timestamp}'

class Genre(models.Model):
    genre = models.CharField(max_length=50)
    books = models.ManyToManyField(Book, blank=True)
    
    slug = models.SlugField()
    
    def __str__(self):
        return self.genre

code/matt/django/lab02/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from time import sleep

# from .models import 

# def index(request):
#     context = {
#         'message': 'blaahhhhhh',
#     }
#     return render(request, 'accounts/index.html', context)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('library:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def success(request):
    ...
    sleep(5)
    return redirect('library:index')

def profile(request):
    ...

code/matt/django/lab02/library/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import Author, Book, Checkout, Genre

def index(request):
    authors = Author.objects.all
    books = Book.objects.all
    context = {
        'message': 'Welcome to the Library!',
        'authors': authors,
        'books': books,
    }
    return render(request, 'library/index.html', context)

def authors(request):
    authors = Author.objects.all
    context = {
        'authors': authors,
    }
    return render(request, 'library/authors.html', context)

def author_detail(request, slug):
    author = Author.objects.get(slug=slug)
    books = Book.objects.filter(author=author)
    context = {
        'author': author,
        'books': books,
    }
    return render(request, 'library/author_detail.html', context)

def books(request):
    books = Book.objects.all
    context = {
        'books': books,
    }
    return render(request, 'library/books.html', context)

def book_detail(request, slug):
    book = Book.objects.get(slug=slug)
    author = book.author
    check_history = Checkout.objects.filter(book=book)
    status = check_history.last()
    if not status:
        same_user = False
    elif str(status.user) == str(request.user):
        same_user = True
    else:
        same_user = False
    genres = Genre.objects.filter(books=book)
    if request.method == 'POST':
        status_update = request.POST.get('status_update')
        user_name = request.user
        Checkout.objects.create(
            book=book,
            user=user_name,
            checkout=status_update,
        )
        return redirect('library:book_detail', slug=slug)
    context = {
        'book': book,
        'author': author,
        'check_history': check_history,
        'genres': genres,
        'status': status,
        'same_user': same_user,
    }
    return render(request, 'library/book_detail.html', context)

def history(request):
    check_history = Checkout.objects.all
    context = {
        'history': check_history,
    }
    return render(request, 'library/history.html', context)

def genre(request, slug):
    genre = Genre.objects.get(slug=slug)
    books = Book.objects.filter(genre=genre)
    context = {
        'genre': genre,
        'books': books,
    }
    return render(request, 'library/genre.html', context)

code/matt/django/lab02/library/templates/library/author_detail.html
{% extends "base_generic.html" %}

{% block title %}: {{ author }}{% endblock %}

{% block content %}
    <h1>{{ author }}</h1>
    <ul>
        {% for book in books %}
        <li><a href="{% url 'library:book_detail' book.id %}">{{ book }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

code/matt/django/lab02/library/templates/library/authors.html
{% extends "base_generic.html" %}

{% block title %}: Authors{% endblock %}

{% block content %}
    <h2><a href="{% url 'library:authors' %}">Authors:</a></h2>
    <ul>
        {% for author in authors %}
        <li><a href="{% url 'library:author_detail' author.id %}">{{ author }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

code/matt/django/lab02/library/templates/library/book_detail.html
{% extends "base_generic.html" %}

{% block title %}: {{ book }}{% endblock %}

{% block content %}
    <h1>{{ book }}</h1>
    <h2>{{ author }}</h2>

    <h3>Current Checkout Status:</h3>
    {% if status.checkout %}
    <p>Checked Out</p>
    <h3>Check back in:</h3>
    {% else %}
    <p>Available</p>
    <h3>Check out:</h3>
    {% endif %}
    <form action="{% url 'library:book_detail' book.id %}" method="POST">
        {% csrf_token %}
        <label for="user_name">User name:</label>
        <input type="text" name="user_name">
        {% if status.checkout %}
        <input type="hidden" value="False" name="status_update">
        <button type="submit">Check In</button>
        {% else %}
        <input type="hidden" value="True" name="status_update">
        <button type="submit">Check Out</button>
        {% endif %}
    </form>
    <h3>
        Check In/Out History:
    </h3>
    <table>
        <thead>
            <th>User</th>
            <th>Date & Time</th>
            <th>In/Out</th>
        </thead>
        {% for item in check_history reversed %}
        <tr>
            <td>{{ item.user }}</td>
            <td>{{ item.timestamp }}</td>
            <td>{% if item.checkout %} OUT {% else %} IN {% endif %}</td>
        </tr>
        {% endfor %}
    </table>
    <h3>
        Genres:
    </h3>
    <ul>
        {% for genre in genres %}
        <li>{{ genre }}</li>
        {% endfor %}
    </ul>
{% endblock %}

code/matt/django/lab02/library/templates/library/books.html
{% extends "base_generic.html" %}

{% block title %}: Books{% endblock %}

{% block content %}
    <h2><a href="{% url 'library:books' %}">Books:</a></h2>
    <ul>
        {% for book in books %}
        <li><a href="{% url 'library:book_detail' book.id %}">{{ book }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

code/matt/django/lab02/library/templates/library/index.html
{% extends "base_generic.html" %}

{% block title %}: Home{% endblock %}

{% block content %}
    <h1>{{ message }}</h1>
    <h2><a href="{% url 'library:authors' %}">Authors:</a></h2>
    <ul>
        {% for author in authors %}
        <li><a href="{% url 'library:author_detail' author.id %}">{{ author }}</a></li>
        {% endfor %}
    </ul>
    <h2><a href="{% url 'library:books' %}">Books:</a></h2>
    <ul>
        {% for book in books %}
        <li><a href="{% url 'library:book_detail' book.id %}">{{ book }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

{% block home_link %}
{% endblock %}