code/chris/django/labs/lab03/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
]

code/chris/django/labs/lab03/posts/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='home'),
    path('chirps/<str:author>', views.profile, name='profile'),
]

code/chris/django/labs/lab03/users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
]

code/chris/django/labs/lab03/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='Posts', null=True)
    content = models.CharField(max_length=200)
    date_written = models.DateTimeField('date chirped', default=datetime.now)
    
    class Meta:
        verbose_name_plural = 'Posts'
    
    def __str__(self):
        return f'{self.author} tweet #{self.id}'

code/chris/django/labs/lab03/users/models.py
from django.db import models

# class User(models.Model):
#     name = models.CharField(max_length=40)

#     def __str__(self):
#         return self.name

code/chris/django/labs/lab03/posts/forms.py
from django import forms
from django.forms import ModelForm
from django import forms


from .models import Posts

class PostsForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control mx-3'
            }),
            'name': 'Chirp',
        }

code/chris/django/labs/lab03/posts/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from .forms import PostsForm
from .models import Posts

def index(request):
    if request.method == 'POST':
        # I need to get the users info to save into the form.
        form = PostsForm(request.POST)
        print(form)
        if form.is_valid():
            chirp = form.save(commit=False)
            chirp.author = request.user
            chirp.date_written = datetime.now()
            chirp.save()
            return redirect('posts:home')
        else:
            message = 'Invalid Fields Provided.'
    form = PostsForm()
    print(form)
        
    posts = Posts.objects.all()
    context = {
        'posts': posts,
        'form': form,
    }
    return render(request, 'posts/index.html', context)

def profile(request, author:str):
    author = User.objects.get(username=author)
    context = {
        'author': author,
    }
    return render(request, 'posts/profile.html', context)
    
# def chirp(request):
    # if request.method == 'POST':
    #     form = PostsForm(request.POST)
    #     print(form)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('posts:chirp')

code/chris/django/labs/lab03/users/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def index(request):
    return render(request, 'posts/index.html')

def login_user(request):
    message = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('posts:home')
        else:
            message = 'login failed'
    context = {
        'message': message,
    }
    return render(request, 'users/login.html', context)

def logout_user(request):
    logout(request)
    return redirect('posts:home')

def signup(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password1 = request.POST.get('password1')
        message = ''
        if password != password1:
            message += 'Passwords do not match. '
        if User.objects.filter(username=username).exists():
            message += 'Username already exists. '
        if message:
            message += 'Please try again.'
        else:
            user = User.objects.create_user(username=username, password=password)
            login(request, user)
            return redirect('posts:home')
        context = {'message': message,}
    return render(request, 'users/signup.html', context)

code/chris/django/labs/lab03/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
<title>Home</title>
{% endblock %}

{% block content %}
<main class="justify-content-center">

    {% if request.user.is_authenticated %}
    
        <div class="container justify-content-center mb-3">
            <div class="row">
            <form action="" method="POST" enctype="multipart/form-data">
                <div class="justify-content-center mb-3">
                {% csrf_token %}
                
                {{ form.content }}
                
                </div>
                <input type="submit" value="Chirp!">

            </form>
            </div>
        </div>
    

    {% endif %}

    {% for post in posts reversed %}
    <div class="container mb-4 text-center shadow bg-body rounded">
        <div class="container text-start"><h3>{{ post.content }}</h3></div>
        <div class="text-start">-Chirped by <a href="{% url 'posts:profile' post.author %}">{{ post.author }}</a> on {{post.date_written}}</div>
    </div>
    {% endfor %}

</main>
{% endblock %}

code/chris/django/labs/lab03/posts/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
<title>{{ author }}'s Chirps</title>
{% endblock %}

{% block content %}
{% for post in author.Posts.all reversed %}
<div class="container mb-4 text-center shadow bg-body rounded">
    <div class="container text-start"><h3>{{ post.content }}</h3></div>
    <div class="text-start">-Chirped by <a href="{% url 'posts:profile' post.author %}">{{ post.author }}</a> on {{post.date_written}}</div>
</div>
{% endfor %}

{% endblock %}