code/logan/django/lab03/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls'))
]

code/logan/django/lab03/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
path('', views.index, name='index'),
path('posts/world', views.world, name='world'),
path('posts/profile', views.profile, name='profile'),
path('posts/profileextend', views.profileextend, name='profileextend'),
path('posts/worldextend', views.worldextend, name='worldextend'),
]

code/logan/django/lab03/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('user_login/', views.user_login, name="user_login"),
]

code/logan/django/lab03/users/models.py
from django.db import models

# Create your models here.

code/logan/django/lab03/users/forms.py
from django.forms import ModelForm
from django import forms

from django.contrib.auth.models import User

# class SignupForm(ModelForm):
#     """
#     I'm not actually using this, but I made it so it's staying.
#     """
#     class Meta:
#         model = User
#         fields = [ 'username', 'password', 'password' ] # damn it didn't work

# class LoginForm(ModelForm):
#     """
#     I'm not actually using this, but I made it so it's staying.
#     """
#     class Meta:
#         model = User
#         fields = [ 'username', 'password']
    

code/logan/django/lab03/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
# from posts.forms import LoginForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponse, HttpRequest

def signup(request):
    message = ""
    if request.method == "POST":
        # message = ""
        form = UserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            message += "Sign-up successful!"
        else:
            message += "Sign-up unsuccessful.  Please try again."

    form = UserCreationForm
    context = {
        'form': form, 
        'message':message
        }
    return render(request, 'users/signup.html', context)

# def login(request):
#     user = None
#     form = AuthenticationForm(data = request.POST)
#     if form.is_valid():
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         return redirect("/posts/world")
#     else:
#         print("Not valid!")
#         return redirect("/")




def user_login(request):
    user = None
    form = AuthenticationForm(data = request.POST)
    if form.is_valid():
        print("form is valid!")
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(request, username=username, password=password)
    # else:
    #     print(form.errors)
    if user != None:
        login(request, user)
        return redirect("/posts/worldextend")
    else:
        print("Not valid!")
        return redirect("/")























###############################
#SCRAP


# Based heavily on Pete's examples on Github

# def login_user(request):
#     context = {}
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect('') # might need to fix this... 'posts:home'

# def logout_user(request):
#     logout(request)
#     return redirect('') # double check these... 'posts:home'

# def signup(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password1 = request.POST.get('password1')
#         password2 = request.POST.get('password2')

#         message = ''
#         if password1 != password2:
#             message += "Passwords do not match."

#         if User.objects.filter(username=username).exists():
#             message += "Username already taken."

#         if message:
#             message += "Please try again." # pretty much all pete, good stuff lol
        
#         else:
#             user = User.objects.create_user(username=username, password=password1)
#             login(request, user)
#             return redirect('') # 'posts:home' ?
#     context = {'message': message}
#     return render(request, 'users/signup.html', context)

# def signup(request):
#     message = ""
#     if request.method == "POST":
#         # message = ""
#         form = SignupForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#         # Do I need another return field here??

#     form = SignupForm()    
#     context = {'form': form}
#     return render(request, 'users/signup.html', context)


# def login(request):
#     user = None
#     form = AuthenticationForm(request.POST)
#     if form.is_valid():
#         # print("form is valid!")
#         username = form.cleaned_data['username']
#         password = form.cleaned_data['password']
#         user = authenticate(request, username=username, password=password)
#     # else:
#     #     print(form.errors)
#     if user is not None:
#         login(request, user)
#         return redirect("/posts/world")
#     else:
#         print("Not valid!")
#         return redirect("/")

code/logan/django/lab03/users/templates/users/signup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign-Up</title>

    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">

    <style>

        h1{font-family: 'Lato', sans-serif; color:whitesmoke}
        h2{font-family: 'Lato', sans-serif; color:#137752}
        body{background-color: whitesmoke;}

    </style>




</head>
<body>

    <header class="bg-dark-green fixed w-100 ph3 pv3 pv4-ns ph4-m ph5-l">

        <h1 class = "tc"><b>Chirp</b></h1>

    </header>
    
    <main class = "pt7 flex items-center flex-column">

    <h2 class = "dark-green">Sign Up</h2>

    <br>
    <br>
    <form action="{% url 'users:signup' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}    
        <input type="submit" value="Log in">
    </form>

    <br>
    <br>

    <h2 class = "red">{{message}}</h2>
    
    <br>
    <br>
    
    <h2><a href = "/"> Home </a></h2>
    </main>


    <footer class = "tr pr6 pt7">
        <h2> © 2022 Birdhouse</h2>

    </footer>



</body>
</html>